which_classifier:
  type: svm
  parameters: { 'kernel': 'rbf',
                'metric': 'f1_macro'
  }

extract_basic_features: False
basic_features_params:
  mid_window: 1
  mid_step: 1
  short_window: 0.05
  short_step: 0.01

extract_nn_features: True
model_paths: ['pretrained_CNNs/YOUR_MODEL_1',
              'pretrained_CNNs/YOUR_MODEL_2',
              'pretrained_CNNs/YOUR_MODEL_3',
              '...']
download_models: True
google_drive_ids: ['GOOGLE_DRIVE_ID_OF_MODEL_1',
                   'GOOGLE_DRIVE_ID_OF_MODEL_2',
                   'GOOGLE_DRIVE_ID_OF_MODEL_3',
                   '...']
n_components: 100
segment_step: 5

